name: Deploy to OVH 

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: FTP Deploy
        uses: samkirkland/ftp-deploy-action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /www/
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            .github/
            README.md